Add search.php endpoint
concretecms/documentation.concretecms.org pull request #55
Opened 2022-08-17 01:28 UTC by wordish

2022-08-17 01:59 UTC, KorvinSzanto requested changes
This likely won't work in our hosting environment because we only allow index.php as an entry point by default IIRC. You could refactor this to be a route inline in app.php as an alternative otherwise we'll probably need to add a location block in nginx to support this endpoint.

Good idea, seems like a valuable addition to the api docs 👍

2022-08-17 01:59 UTC, KorvinSzanto commented on public/search.php
> +ini_set('include_path', __DIR__ . "/../../../vendor" . PATH_SEPARATOR . get_include_path());
`include_path` effects include/require calls so this doesn't have any effect since there aren't any past this line

2022-08-17 01:59 UTC, KorvinSzanto commented on public/search.php
> +    if ($version->isGreaterThan($latestVersion)) {
This is a good way to do this, another good way that avoids the dependency is [`version_compare`](https://www.php.net/manual/en/function.version-compare.php)

2022-08-17 01:59 UTC, KorvinSzanto commented on public/search.php
> +$keywords = $_GET['keywords'] ?: '';
This can trigger a warning, better to use the null coalesce operator than a ternary since the array key might not be set
```suggestion
$keywords = $_GET['keywords'] ?? '';
```

2022-08-17 01:59 UTC, KorvinSzanto commented on public/search.php
> +die;
No need to add die at the end in the HTTP SAPI since the script dies by default when it reaches the end of the file it can be helpful in the CLI SAPI since you can set the output code.

2022-09-23 20:07 UTC, wordish commented
@KorvinSzanto @aembler updated based on feedback

2022-09-23 20:26 UTC, KorvinSzanto approved these changes

2022-09-23 20:26 UTC, merged

2022-09-23 20:27 UTC, KorvinSzanto commented
Looks good to me, nice job 👍